# Configuração específica para Inception V3

# Configurações do Dataset
data:
  root_path: "C:/data/processed/deepHP_50K"
  indices_path: "/src/indices/indices.pth"
  num_classes: 2
  class_names: ["negative", "positive"]
  
# Divisão do Dataset
splits:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  stratified: true
  seed: 42
  
# Transformações 
transforms:
  img_size: 299  
  normalize: true
  augmentation:
    train: "light"  
    val: "none"
    
# DataLoader
dataloader:
  batch_size: 24  
  num_workers: 0
  pin_memory: false
  persistent_workers: false

# Modelo Inception V3
model:
  name: "inception_v3"
  pretrained: true
  freeze_layers: false
  dropout: 0.5
  
# Treinamento otimizado para Inception V3
training:
  epochs: 100
  learning_rate: 0.00001  
  weight_decay: 0.0005
  optimizer: "adam"
  scheduler:
    name: "reduce_on_plateau"
    patience: 5
    factor: 0.3
    min_lr: 0.0000001
  early_stopping:
    patience: 15
    min_delta: 0.001
    
# Experimento
experiment:
  name: "inception_v3_isolated_v3"
  save_dir: "models/saved/inception_v3"
  log_dir: "logs/inception_v3"
  results_dir: "results/inception_v3"
  save_best_only: true
  verbose: true
  
# Reprodutibilidade
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false

# Monitoramento
monitoring:
  enabled: true              
  interval: 30           